In [1]:
%reload_ext dotenv
%dotenv

from aocd import get_data
from aocd import submit
import numpy as np

day = 8
year = 2022

lines = get_data(day=day, year=year).split('\n')

In [2]:
sample = ['30373', '25512', '65332', '33549', '35390']

In [3]:
inp = np.array([list(x) for x in sample]).astype('int')

In [4]:
right = []
for x in inp:
    small = -1
    row = []
    for y in x:
        if y > small:
            small = y
            row.append(True)
        else:
            row.append(False)
    right.append(row)
right = np.array(right)
right

array([[ True, False, False,  True, False],
       [ True,  True, False, False, False],
       [ True, False, False, False, False],
       [ True, False,  True, False,  True],
       [ True,  True, False,  True, False]])

In [5]:
down = []
for x in inp.T:
    small = -1
    row = []
    for y in x:
        if y > small:
            small = y
            row.append(True)
        else:
            row.append(False)
    down.append(row)
down = np.array(down).T
down

array([[ True,  True,  True,  True,  True],
       [False,  True,  True, False, False],
       [ True, False, False, False, False],
       [False, False, False, False,  True],
       [False, False, False,  True, False]])

In [6]:
left = []
for x in np.flip(inp, 1):
    small = -1
    row = []
    for y in x:
        if y > small:
            small = y
            row.append(True)
        else:
            row.append(False)
    left.append(row)
left = np.flip(left, 1) 
left

array([[False, False, False,  True,  True],
       [False, False,  True, False,  True],
       [ True,  True, False,  True,  True],
       [False, False, False, False,  True],
       [False, False, False,  True,  True]])

In [7]:
up = []
for x in np.flip(inp, 0).T:
    small = -1
    row = []
    for y in x:
        if y > small:
            small = y
            row.append(True)
        else:
            row.append(False)
    up.append(row)
up = np.flip(np.array(up).T, 0) 
up

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [ True, False, False, False, False],
       [False, False,  True, False,  True],
       [ True,  True,  True,  True,  True]])

In [8]:
# submit((down+left+right+up).sum(), part="a", day=day, year=year)

In [12]:
inp

array([[3, 0, 3, 7, 3],
       [2, 5, 5, 1, 2],
       [6, 5, 3, 3, 2],
       [3, 3, 5, 4, 9],
       [3, 5, 3, 9, 0]])

In [13]:
right

array([[ True, False, False,  True, False],
       [ True,  True, False, False, False],
       [ True, False, False, False, False],
       [ True, False,  True, False,  True],
       [ True,  True, False,  True, False]])

In [18]:
right.astype(int)[0]

array([1, 0, 0, 1, 0])

In [89]:
right.astype(int)[0][7:]

array([], dtype=int64)

In [104]:
final = []
for iy, y in enumerate(right.astype(int)[3]):
    count = 0
    for z in right.astype(int)[3][iy+1:]:
        if z==0:
            print (z, 'add one')
            count += 1
        elif z==1:
            print (z, 'add one but leave')
            count += 1
            final.append(count)
            count = 0 

0 add one
1 add one but leave
0 add one
1 add one but leave
1 add one but leave
0 add one
1 add one but leave
0 add one
1 add one but leave
1 add one but leave


In [105]:
final

[2, 2, 1, 2, 2, 1]

In [22]:
right

array([[ True, False, False,  True, False],
       [ True,  True, False, False, False],
       [ True, False, False, False, False],
       [ True, False,  True, False,  True],
       [ True,  True, False,  True, False]])