In [1]:
%reload_ext dotenv
%dotenv

from aocd import get_data
from aocd import submit
import numpy as np

day = 8
year = 2022

lines = get_data(day=day, year=year).split('\n')

In [2]:
sample = ['30373', '25512', '65332', '33549', '35390']

In [3]:
inp = np.array([list(x) for x in sample]).astype('int')

In [4]:
right = []
for x in inp:
    small = -1
    row = []
    for y in x:
        if y > small:
            small = y
            row.append(True)
        else:
            row.append(False)
    right.append(row)
right = np.array(right)
right

array([[ True, False, False,  True, False],
       [ True,  True, False, False, False],
       [ True, False, False, False, False],
       [ True, False,  True, False,  True],
       [ True,  True, False,  True, False]])

In [5]:
down = []
for x in inp.T:
    small = -1
    row = []
    for y in x:
        if y > small:
            small = y
            row.append(True)
        else:
            row.append(False)
    down.append(row)
down = np.array(down).T
down

array([[ True,  True,  True,  True,  True],
       [False,  True,  True, False, False],
       [ True, False, False, False, False],
       [False, False, False, False,  True],
       [False, False, False,  True, False]])

In [6]:
left = []
for x in np.flip(inp, 1):
    small = -1
    row = []
    for y in x:
        if y > small:
            small = y
            row.append(True)
        else:
            row.append(False)
    left.append(row)
left = np.flip(left, 1) 
left

array([[False, False, False,  True,  True],
       [False, False,  True, False,  True],
       [ True,  True, False,  True,  True],
       [False, False, False, False,  True],
       [False, False, False,  True,  True]])

In [7]:
up = []
for x in np.flip(inp, 0).T:
    small = -1
    row = []
    for y in x:
        if y > small:
            small = y
            row.append(True)
        else:
            row.append(False)
    up.append(row)
up = np.flip(np.array(up).T, 0) 
up

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [ True, False, False, False, False],
       [False, False,  True, False,  True],
       [ True,  True,  True,  True,  True]])

In [8]:
submit((down+left+right+up).sum(), part="a", day=day, year=year)